name: Tests

on:
  push:
    branches: ["master"]
    paths-ignore:
      - .editorconfig
      - LICENSE
      - README.md
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.11"
          cache: pip
      - name: Upgrade pip
        run: |
          python -m pip install pip --upgrade
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Run tests and get coverage
        run: |
          coverage run runtests.py
          coverage xml -o ./coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          files: ./coverage.xml
          flags: unittests
          verbose: true
